### ISSUE TITLE
Feature request: Enable AP+STA mode

### ISSUE THREAD

**Issue by buserp** [Puara/MPU#4]
Currently, the MPU ships in AP mode, allowing wireless clients to connect to it but not allowing the MPU to connect to the WAN.

I suggest that the MPU be put by default in AP+STA mode, allowing it simultaneously to act as a WiFi hotspot and to connect to a wireless network, allowing for WAN access.

This would be useful in a performance context if, for example, you had audience members who wished to participate using a webapp, but didn't want to connect to a separate WiFi network. WAN traffic from the audience members could be routed to the MPU, while also allowing instruments (such as the T-Stick) to connect to the access point afforded by the MPU.

One tutorial for doing this on Raspberry Pi can be found here: https://docs.raspap.com/ap-sta/.

**Comment by edumeneses** [comment]
That's indeed useful, but I don't know how reliable the WiFi module is in dual mode. I remembered trying this in the past with poor results (intermittent disconnections, unreliable signal). I have to run some tests before implementing it.

Regardless, if reliable interaction using WiFi is required, I usually suggest a dedicated router that provides a stable and stronger signal.

**Comment by edumeneses** [comment]
I will close this issue as the OS part of the MPU will migrate soon to another project. We will explore solutions of AP/STA modes then.
